listener 1883 0.0.0.0
allow_anonymous false
password_file C:\Program Files\mosquitto\passwd.txt

connection bridge_to_B
address 10.0.0.2:1883
remote_username mqttuser
remote_password mqtt1234
topic home/nodeB/humidity in 0
topic home/nodeA/temp out 0
bridge_attempt_unsubscribe false
